image: node:latest

services:
  - mongo

variables:
  MONGO_DATABASE: db

  Host: mongo
  Database: db


stages:
 - build
 - test
  
install_dependencies:
 stage: build
 script:
  - npm install
 artifacts:
  paths:
   - tig_client/node_modules/
   - node_modules/
   
testing:
 stage: test
 script:
  - chmod 0777 ./node_modules/.bin/mocha
  - npm run test
 artifacts:
  paths:
   - tig_client/