image: node:latest

stages:
 - build
 - test
  
install_dependencies:
 stage: build
 script:
  - npm install
 artifacts:
  paths:
   - node_modules/
   
testing:
 stage: test
 services:
  - mongo:latest

 variables:
  MONGO_DATABASE: test

  Host: cluster0-e8bno.gcp.mongodb.net
  Database: test
  
 script:
  - chmod -R +x node_modules/.bin
  # next lines were supposed to be for testing with cypress
  #- chmod -R +x tig_client/node_modules/.bin
  #- find tig_client/node_modules/ -type f -name xdg-open -exec chmod a+x {} \;
  #- apt-get install xvfb
  #- node_modules/.bin/cypress install
  - npm run test