image: node:latest

stages:
 - build
 - prepare
 - test
  
install_dependencies:
 stage: build
 script:
  - npm install
 artifacts:
  paths:
   - tig_client/node_modules/
   - node_modules/

pre_testing:
 stage: prepare
 script:
  - chmod -R u+x node_modules/.bin
  - chmod -R u+x tig_client/node_modules/.bin
   
testing:
 stage: test
 services:
  - mongo:latest

 variables:
  MONGO_DATABASE: test

  Host: cluster0-e8bno.gcp.mongodb.net
  Database: test
  
 script:
  - npm run test
 artifacts:
  paths:
   - tig_client/